### PR TITLE
removed old ref. to gabe's blog

### PR DESCRIPTION
**Pull request by zekiel**
//cc @yegg @moollaza

### CODE REVIEW

**Comment by moollaza** [comment]
@zekiel could make the URL: http://daringfireball.net/#SiteSearch and then it'll go all the way to the bottom of the page automatically

**Comment by moollaza** [comment]
But this LGTM :+1:

**Comment by moollaza** [comment]
Fixed it myself. The magic of Git branches.

**Comment by zekiel** [comment]
oh nice -- i didn't see the anchor

**Pull request merged**
