### PR TITLE
Updates to API static page

### PR DESCRIPTION
**Pull request by tagawa**
The new message at the top will hopefully reduce some confusion for developers looking for a full results API.

Also, my editor has removed lots of trailing spaces.

### CODE REVIEW

**Comment by tagawa** [comment]
Added a new Rust wrapper by @Aaronepower to the list of libraries.

**Comment by tagawa** [comment]
Hi @jbarrett. I just added a new Node library to this PR. Would you be able to review when you have a moment please?

**Comment by jbarrett** [comment]
👍 Thanks, @tagawa!

**Comment by tagawa** [comment]
Guroovy! Thanks @jbarrett

**Pull request merged**
