### PR TITLE
Add ids to major sections of DDH

### PR DESCRIPTION
**Pull request by alohaas**
@russellholt 
We need to link to the community section from Duck.co. 
It would be helpful to be able to link to any section in the future as well.
Ids are as follows, beginning after the hero screenshot carousel:
- `power-of-ias`
- `get-involved`
- `get-help`
- `join-community`<--- this is the one @jagtalon will want to link to from Duck.co
- `plaudits` 
- `ia-suggestions`

### CODE REVIEW

**Comment by jagtalon** [comment]
:+1:

**Comment by alohaas** [comment]
@bsstoner we'll need some support getting this live.

**Comment by bsstoner** [comment]
Nice! You just need to release publisher and bump the pin on bttf. Want to walk through how to do it?

**Comment by alohaas** [comment]
@bsstoner would love a walk through. I'll follow up on chat.

**Pull request merged**
