### PR TITLE
added DDH link to IA section of Tour

### PR DESCRIPTION
**Pull request by zekiel**
//cc @sdougbrown  can you please review and let me know if I botched it? :)

### CODE REVIEW

**Comment by sdougbrown** [comment]
Probably should change 'finding a movies' to 'finding a movie'. :smile:

**Comment by zekiel** [comment]
ok I give up--can't find what you mean :) 


this line: 


<p class="tour-text__p">Instant Answers help you find what you're looking for in fewer clicks. Everything from a <a href="/?q=stopwatch" target="ddg_stopwatch">stopwatch</a> for your workout to finding <a href="/?q=movies+with+Chuck+Norris" target="ddg_chuck_movies">movies with Chuck Norris</a>

**Comment by sdougbrown** [comment]
hah I totally misread it, sorry.

:+1:

**Comment by zekiel** [comment]
:bow:

**Pull request merged**
