### PR TITLE
Remove T shirt link from /spread

### PR DESCRIPTION
**Pull request by jbarrett**
Cc: @bsstoner @chrismorast @zekiel

### CODE REVIEW

**Comment by jbarrett** [comment]
Assigning @bsstoner - I think this will need to go out before the duck.co changes go live (which should be early next week).

Thanks!

**Comment by bsstoner** [comment]
Requires internal changes too since we were doing the referrer checks and only showing that section via JS. Created PR here: https://dub.duckduckgo.com/core/ddg/pull/5393

**Comment by bsstoner** [comment]
:+1:

**Comment by jbarrett** [comment]
Many thanks @bsstoner!

**Pull request merged**
