### PR TITLE
added newsletter anchor

### PR DESCRIPTION
**Pull request by zekiel**
//cc @sdougbrown  can you please merge if it looks ok? Otherwise, I will make any necessary updates-don't want to distract.

### CODE REVIEW

**Comment by sdougbrown** [comment]
The class name should just be 'anchor', otherwise this is fine. :)

**Comment by zekiel** [comment]
updated!

**Comment by sdougbrown** [comment]
:+1:

**Comment by zekiel** [comment]
thx @sdougbrown  Can you please release publisher to get this and the broken image in the DDH footer?

**Pull request merged**
