### PR TITLE
Various updates (mainly cleaned markup/HTML). Also, first DDG-related PR :D

### PR DESCRIPTION
**Pull request by ScreapDK**
Some changed I wanted to see in the source code of my search engine of choice. Wow, I still can't believe I'm say that! :D

### CODE REVIEW

**Comment by ScreapDK** [comment]
Hi @MariagraziaAlastra! I want to do this still and I finally have some time to get it figured out! I hope you can/will help me? :)

>I know that it seems like the easiest thing to do, but it's not like that, really. Using Git from the command-line is so much easier, and most of the times it's always about the same bunch of commands.

>What OS are you using? If you use Windows there's GitHub for Windows, which comes with a handy git shell!

I have cloned the repo to my local machine, installed GitHub for Windows, and I have the repo open in the file manager, and have open Git shell (located at the repo master) with the hell of GitHub for Windows.

Now I just need to find out how to rebase (the concept you explained), from the `master`-branch to the `ScreapDK/various-updates`-branch. Can you tell me how I do that?

Yes, I read the "rebase"-section in the tutorial you linked me to [on 10 Sep 2014](#issuecomment-55103829), I'm just not able to out the examples what exact syntax I shall use.

BTW, congrats on the employment at DDG (^_^), I saw you were added to the about-page! :D
I am remembering right that you were first a Community Leader, for a (short) while, right?

**Comment by ScreapDK** [comment]
Sorry, didn't mean to close the PR. Clumpsy me :/

**Comment by MariagraziaAlastra** [comment]
Hey @ScreapDK!

I know, rebasing is a little bit tricky. I'll try to come up with an easier solution, but I need to experiment a bit, first.
I'll get back to you on Monday on even sooner if I can, is that ok?

>BTW, congrats on the employment at DDG (^_^), I saw you were added to the about-page! :D
I am remembering right that you were first a Community Leader, for a (short) while, right?

Awww, thank you! Yes, you remember correctly :)

**Comment by ScreapDK** [comment]
@MariagraziaAlastra Well, I'm game about/for/on/??? learning how to rebase! It sounds like the right tool in this case. :)

**Comment by MariagraziaAlastra** [comment]
@ScreapDK Ok, so: let's try with a regular merge instead, since it's easier to do and it's also the usual way to tackle conflicts. 

Before that, however, clone your fork and add the official duckduckgo-publisher repo to the remote origins, so you can pull the latest changes from there: 

`git clone https://github.com/ScreapDK/duckduckgo-publisher.git`
`git remote add upstream https://github.com/duckduckgo/duckduckgo-publisher.git`

"upstream" is the name we'll use from now to reference the repo.

Now type `git pull upstream master` to get the latest version of the master branch. You will see this message:

```
From https://github.com/duckduckgo/duckduckgo-publisher                                                                                                       
 * branch            master     -> FETCH_HEAD                                                                                                                 
Removing share/site/duckduckgo/yui_body_header_settings.tx                                                                                                    
Removing share/site/duckduckgo/whatsnew.tx                                                                                                                    
CONFLICT (modify/delete): share/site/duckduckgo/supportus.tx deleted in b315a9165afd4eb779d5ee8b92262292b4d0de12 and modified in HEAD. Version HEAD of share/s
ite/duckduckgo/supportus.tx left in tree.                                                                                                                     
Auto-merging share/site/duckduckgo/search_form_homepage.tx                                                                                                    
CONFLICT (content): Merge conflict in share/site/duckduckgo/search_form_homepage.tx                                                                           
Removing share/site/duckduckgo/meta/whatsnew.tx                                                                                                               
Removing share/site/duckduckgo/meta/support.tx                                                                                                                
Auto-merging share/site/duckduckgo/meta/index.tx                                                                                                              
CONFLICT (content): Merge conflict in share/site/duckduckgo/meta/index.tx                                                                                     
Removing share/site/duckduckgo/meta/goodies-metaheader.tx                                                                                                     
Auto-merging share/site/duckduckgo/meta/base.tx                                                                                                               
CONFLICT (content): Merge conflict in share/site/duckduckgo/meta/base.tx                                                                                      
Removing share/site/duckduckgo/menu_inner.tx                                                                                                                  
Removing share/site/duckduckgo/menu_header.tx                                                                                                                 
Auto-merging share/site/duckduckgo/header.tx                                                                                                                  
CONFLICT (content): Merge conflict in share/site/duckduckgo/header.tx                                                                                         
Removing share/site/duckduckgo/goodies.tx                                                                                                                     
Removing share/site/duckduckgo/goodies-in/twitter.tx                                                                                                          
Removing share/site/duckduckgo/goodies-in/topics-in.json                                                                                                      
Removing share/site/duckduckgo/goodies-in/topic.tx                                                                                                            
Removing share/site/duckduckgo/goodies-in/topic-everyday.tx                                                                                                   
Removing share/site/duckduckgo/goodies-in/title.tx                                                                                                            
Removing share/site/duckduckgo/goodies-in/safe.tx                                                                                                             
Removing share/site/duckduckgo/goodies-in/noresults.tx                                                                                                        
Removing share/site/duckduckgo/goodies-in/facebook.tx                                                                                                         
Removing share/site/duckduckgo/goodies-in/README.md                                                                                                           
Removing share/site/duckduckgo/footer_copyright.tx                                                                                                            
Auto-merging lib/DDG/Publisher/Site/Fixtracking/Root.pm                                                                                                       
Auto-merging lib/DDG/Publisher/Site/Duckduckgo/Root.pm                                                                                                        
CONFLICT (content): Merge conflict in lib/DDG/Publisher/Site/Duckduckgo/Root.pm                                                                               
Automatic merge failed; fix conflicts and then commit the result.
```

What this means is that you're being informed about what files contain conflicts, so you can fix them manually. In this case, those files are: 
* share/site/duckduckgo/search_form_homepage.tx
* share/site/duckduckgo/meta/index.tx
* share/site/duckduckgo/meta/base.tx
* share/site/duckduckgo/header.tx
* lib/DDG/Publisher/Site/Duckduckgo/Root.pm 

Open each of them with your favourite editor and fix the conflicts. You'll see something like this:
```html
<: include "meta/title.tx" { title => 'DuckDuckGo' } :>

<<<<<<< HEAD
<meta name="description" content="The search engine that doesn't track you."/>
=======
<meta name="description" content="The search engine that doesn't track you. A superior search experience with smarter answers, less clutter and real privacy.">
>>>>>>> b315a9165afd4eb779d5ee8b92262292b4d0de12
```

The piece of code between `<<<<<<<HEAD` and `=====` is your version, while the other one is current version on the official repo. Just make the necessary changes to the current version and then remove all those symbols. The file content should look more or less like this:
```html
<: include "meta/title.tx" { title => 'DuckDuckGo' } :>

<meta name="description" content="The search engine that doesn't track you. A superior search experience with smarter answers, less clutter and real privacy.">
```

Now save and repeat for each of the files with conflicts.
There's also a file you modified which has been removed, share/site/duckduckgo/supportus.tx, so run `git rm share/site/duckduckgo/supportus.tx`

After fixing all the conflicts, you can now add and commit your changes: first, run `git add .` and then `git commit -a -m` and add a message for the commit, e.g. `git commit -a -m "Fix merge conflicts with master"`.

Now run `git push origin master` to update your master branch, and you're done!

Let me know if you have any questions/issues :)

**Comment by ScreapDK** [comment]
Hey again, @MariagraziaAlastra!

Sorry, but your guide above is simply too complex for a (GIt) noob like me... :(

I've decided that I will delete my fork and then fork it again.

I have downloaded a copy of the current fork, and [archived](https://web.archive.org/web/20150227061306/https://github.com/duckduckgo/duckduckgo-publisher/pull/105/files?diff=split) [this view](https://github.com/duckduckgo/duckduckgo-publisher/pull/105/files?diff=split) of all the changes/changed files.

I'm so sorry that you had to spend/waste your time to explain to me something I still did not understand.

BUT, thanks a lot for trying! :)
I really appreciate it! :D

I'll let you be able to comment before closing this PR.
Feel free to do it if/when you see fit. :)

**Comment by MariagraziaAlastra** [comment]
Hi @ScreapDK!

No worries, you didn't waste my time at all! I'm glad you found a good solution :)
Next time you make changes please do so on another branch, not on the master branch: this way it will be a lot easier to resolve conflicts!

Let me know if you need any help, and have a great weekend! :D

**Pull request closed without merging**
