### PR TITLE
SVG favicon added

### PR DESCRIPTION
**Pull request by J0WI**
Just added SVG favicon, becuse they are awesome.
You may give me a hint what's the right file to use.

### CODE REVIEW

**Comment by moollaza** [comment]
@J0WI thanks, we actually swap in the SVG file, via JS when the client supports it. If you take a look at the homepage you will see we have have the SVG logo displaying!

I'm going to close this because it's not quite necessary, but thanks a lot for contributing! We really appreciate it.

If you interested in developing other stuff, please checkout http://duckduckhack.com

**Comment by J0WI** [comment]
@moollaza this issue is about supporting **SVG favicon**, means using an SVG as the **favicon**.
You currently don't support this feature. Please reopen and review.

**Comment by moollaza** [comment]
@J0WI apologies, I totally misread this.

@sdougbrown any thoughts on this?

**Comment by J0WI** [comment]
Any update on this?
*ping* @sdougbrown

**Comment by moollaza** [comment]
@J0WI thanks for this -- the team just merged a similar PR adding in a new SVG icon

**Comment by J0WI** [comment]
@moollaza I can't see any on https://github.com/duckduckgo/duckduckgo-publisher/blob/master/share/site/duckduckgo/meta/base.tx nor on https://beta.duckduckgo.com/

**Comment by moollaza** [comment]
Apologies, I misread the merged PR.

**Comment by moollaza** [comment]
Doug is no longer with our company -- @bsstoner any thoughts on us using an SVG favicon?

**Comment by bsstoner** [comment]
We can do it. It's not as simple as this though. We'd have to make changes internally too. We also need to make sure it falls back to .png properly in every browser. It's not really supported well in browsers yet either, so it's not really a priority right now imo.

**Comment by J0WI** [comment]
The fallback works out of the box in all common browsers.
There was an issue with Apples syntax for their unstandardized mask-icon, but this has been fixed in their spec.

**Comment by moollaza** [comment]
We are working on favicons elsewhere, internally

**Pull request closed without merging**
