### PR TITLE
Added social media links to About page

### PR DESCRIPTION
**Pull request by tagawa**
Following suggestions by @andrey-p and @chrismorast in https://app.asana.com/0/inbox/42485752355997/248995145166035/249079438970887

about-page_social-media

### CODE REVIEW

**Comment by tagawa** [comment]
mockup_social-media_about-page2

**Comment by andrey-p** [comment]
Thanks @tagawa! One thing I'd personally add is `class="no-visited"` to the links, so that they stay blue even if you've visited them.

Also, I think we need to push the links down a bit from the text. This requires some internal style changes, I'll post an internal note to tell you how.

**Comment by tagawa** [comment]
Thanks @andrey-p. I updated this with your `div` wrapper and extra classes. This should be good to go for now, together with a separate CSS PR to add the extra padding.

**Comment by tagawa** [comment]
mockup_social-media_about-page3

**Comment by andrey-p** [comment]
:+1: Thank you!

**Pull request merged**
